#!/bin/bash

# --- UNIVERSAL DNA SKELETONIZER (TOON 2.1 - DEEP LINK) ---
# Version: 2026.16 | Format: High-Density Sigil Stream
# Fixes: Captured parameters, inheritance, and automation manifests.

TARGET_DIR="${1:-.}"
ABS_TARGET_DIR=$(cd "$TARGET_DIR" && pwd || exit 1)
PROJECT_NAME=$(basename "$ABS_TARGET_DIR")
OUTPUT_FILE="$ABS_TARGET_DIR/project_dna.toon"

detect_folder_stack() {
    local dir=$1
    if   [ -f "$dir/shopify.extension.toml" ]; then echo "Shopify"
    elif [ -f "$dir/Gemfile" ];                then echo "Ruby/Rails"
    elif [ -f "$dir/package.json" ];           then echo "Node.js"
    elif [ -f "$dir/requirements.txt" ] || [ -f "$dir/pyproject.toml" ] || [ -f "$dir/setup.py" ]; then echo "Python"
    elif [ -f "$dir/Cargo.toml" ];             then echo "Rust"
    elif find "$dir" -maxdepth 1 -name "*.go" | grep -q .; then echo "Go"
    elif [ -f "$dir/Justfile" ] || [ -f "$dir/Makefile" ]; then echo "Task-Heavy"
    else echo "Unknown"; fi
}

detect_test_commands() {
    local dir=$1
    local found=0
    if [ -f "$dir/Makefile" ] && grep -q "^test:" "$dir/Makefile" 2>/dev/null; then
        echo "- make test"; found=1
    fi
    if [ -f "$dir/package.json" ] && grep -q '"test"' "$dir/package.json" 2>/dev/null; then
        echo "- npm test"; found=1
    fi
    if [ -f "$dir/pytest.ini" ]; then
        echo "- pytest"; found=1
    elif [ -f "$dir/pyproject.toml" ] && grep -q '\[tool.pytest' "$dir/pyproject.toml" 2>/dev/null; then
        echo "- pytest"; found=1
    fi
    if [ -f "$dir/Cargo.toml" ]; then
        echo "- cargo test"; found=1
    fi
    if find "$dir" -maxdepth 1 -name "*.go" | grep -q .; then
        echo "- go test ./..."; found=1
    fi
    if [ -f "$dir/Gemfile" ]; then
        if grep -q "rspec" "$dir/Gemfile" 2>/dev/null; then
            echo "- bundle exec rspec"; found=1
        elif grep -q "minitest" "$dir/Gemfile" 2>/dev/null; then
            echo "- bundle exec rake test"; found=1
        fi
    fi
    [ $found -eq 0 ] && echo "- (no test commands detected)"
}

detect_entry_points() {
    local dir=$1
    local found=0
    for pattern in main app index server; do
        for ext in .js .ts .py .go .rb .rs; do
            if [ -f "$dir/$pattern$ext" ]; then
                echo "- $pattern$ext: application entry point"; found=1
            fi
            if [ -f "$dir/src/$pattern$ext" ]; then
                echo "- src/$pattern$ext: application entry point"; found=1
            fi
        done
    done
    [ $found -eq 0 ] && echo "- (no standard entry points detected)"
}

CLAUDE_MD_FILE="$ABS_TARGET_DIR/CLAUDE.md"

generate_claude_md() {
    {
        echo "# Project: $PROJECT_NAME"
        echo ""
        echo "## Stack"
        detect_folder_stack "$ABS_TARGET_DIR"
        echo ""
        echo "## Test Commands"
        detect_test_commands "$ABS_TARGET_DIR"
        echo ""
        echo "## Key Entry Points"
        detect_entry_points "$ABS_TARGET_DIR"
        echo ""
        echo "---"
        echo "_Auto-generated by dna.sh. Edit freely._"
    } > "$CLAUDE_MD_FILE"
}

extract_dna() {
    {
        echo "P:$PROJECT_NAME"
        echo "S:$(detect_folder_stack "$ABS_TARGET_DIR")"
        echo "T:$(date +%s)"
        echo "---"

        # Find directories, excluding noisy ones
        find "$ABS_TARGET_DIR" -maxdepth 5 -type d \
            -not -path '*/.*' -not -path '*node_modules*' -not -path '*vendor*' -not -path '*bundle*' -not -path '*tmp*' | sort | while read -r current_dir; do
            
            # Only process folder if it contains files (not just subfolders)
            if ls -p "$current_dir" | grep -v / | grep -qv "project_dna.toon"; then
                CLEAN_DIR=$(echo "$current_dir" | sed "s|$ABS_TARGET_DIR/||")
                [ "$current_dir" == "$ABS_TARGET_DIR" ] && CLEAN_DIR="root"

                echo "§$CLEAN_DIR"
                
                # ! = Manifests (Expanded to include Justfile, Makefile, etc.)
                find "$current_dir" -maxdepth 1 -type f \( -name "package.json" -o -name "Gemfile" -o -name "Justfile" -o -name "Makefile" -o -name "mise.toml" \) | while read -r m; do
                    echo "!$(basename "$m")"
                    # Capture versioning and key dependencies without extra lines
                    grep -E "^[[:space:]]*[\"']?(name|version|ruby|gem|module|import|recipe)[\"']?[:= ]" "$m" | \
                    sed -E 's/[",{}]//g; s/^[[:space:]]*//' | head -n 15 | awk '{print "  " $0}'
                done

                # Symbol Cache with Parameter support (--fields=+S) and Inheritance mapping
                SYM_TMP=$(mktemp)
                ctags --languages=javascript,typescript,ruby,python,rust,go \
                --ruby-kinds=+fmf --python-kinds=+fm --fields=+nKS --excmd=n -f - "$current_dir"/* 2>/dev/null > "$SYM_TMP"

                find "$current_dir" -maxdepth 1 -type f -not -path '*/.*' | sort | while read -r f; do
                    fname=$(basename "$f")
                    [[ "$fname" == "project_dna.toon" ]] && continue
                    
                    # Output the file sigil
                    echo "~$fname"
                    
                    # Output the symbols with stripped path and parameters
                    # Format: >kind:name signature
                    awk -v file_path="$f" -F'\t' '$2 == file_path {
                        split($4, sig, " "); 
                        kind=$4; sub(/:.*/, "", kind);
                        name=$1;
                        # Capture signature/params if available
                        params=""; if(match($0, /signature:\(.*\)/)) { params=substr($0, RSTART+10, RLENGTH-11) }
                        print ">" $4 ":" $1 (params != "" ? "(" params ")" : "")
                    }' "$SYM_TMP" | head -n 15
                done
                rm "$SYM_TMP"
            fi
        done
        
        echo "---"
        echo "TOKENS_EST:$(wc -w < "$OUTPUT_FILE" | awk '{print int($1 * 1.3)}')"

    } > "$OUTPUT_FILE"
}

if ! command -v ctags &>/dev/null; then echo "❌ ctags (universal-ctags) required"; exit 1; fi
extract_dna
echo "✅ TOON 2.1 (Deep-Link) Created: $OUTPUT_FILE"
generate_claude_md
echo "✅ CLAUDE.md generated: $CLAUDE_MD_FILE"